// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veoewwnaxgjpssfhzlaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlb2V3d25heGdqcHNzZmh6bGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTk1NjMsImV4cCI6MjA2OTk5NTU2M30.Lly6yWVvNvcAQ44bbmZlo1kZZwlzbANj_7KIhew2vLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});